### ISSUE TITLE
Will corrosion have a compatibility guarantee?

### ISSUE THREAD

**Issue by biox** [superfly/corrosion#62]
One of the most important marks of software that I implement in production is a backwards compatibility guarantee. Similar to hashicorp's [consul compatibility guarantee](https://developer.hashicorp.com/consul/docs/upgrading/compatibility) or golang's [backwards compatibility promise](https://go.dev/blog/compat). For something as foundational as service discovery, I'd like to have a guarantee that future versions of corrosion won't require a dramatic amount of operator effort to upgrade or become otherwise protocol-incompatible with the running version of corrosion, which could cause all sorts of haywire-ness.

Any thoughts about this, or is it too early in corrosion's life to consider it?

**Comment by biox** [comment]
(fwiw, i have been excited for corrosion for a long time, and i do have specific use-cases in mind. i think that eventually-consistent service discovery is _the_ way forward for scaleable service discovery platforms)

**Comment by jeromegn** [comment]
To add more details:
- The database schema is up to the user and can never be destructive (currently)
- The data transmission schema is heavily versioned and we chose a format you can append to (enum variant, struct fields) without introducing a breaking change
- The internal database schema is SQLite and works with migrations, updates should be transparent
- The cr-sqlite dependency is a different matter. There hasn't always been migrations paths when introducing breaking changes there, but we're in close contact with the creator and we can figure it out

There's an upcoming cr-sqlite change to significantly reduce disk space usage and that should be released soon. Since  nobody is using Corrosion yet (unless some very motivated people started experimenting) this could be a breaking change _already_, in which case we'll yank the older version. It might be a migrate-able change, I'm not sure.

Pre-1.0, there's a risk of a breaking change, but as @mrkurt said, we're also running this so we'll need a migration path too.
